title: Course of ideas
description: Here are some ideas you never thought possible
template:
  repo: course-of-ideas-template
  name: course-of-ideas
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
